# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/boss/CLionProjects/mozquic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/boss/CLionProjects/mozquic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/boss/CLionProjects/mozquic/CMakeFiles /home/boss/CLionProjects/mozquic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/boss/CLionProjects/mozquic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mozquic

# Build rule for target.
mozquic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mozquic
.PHONY : mozquic

# fast build rule for target.
mozquic/fast:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/build
.PHONY : mozquic/fast

API.o: API.cpp.o

.PHONY : API.o

# target to build an object file
API.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/API.cpp.o
.PHONY : API.cpp.o

API.i: API.cpp.i

.PHONY : API.i

# target to preprocess a source file
API.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/API.cpp.i
.PHONY : API.cpp.i

API.s: API.cpp.s

.PHONY : API.s

# target to generate assembly for a file
API.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/API.cpp.s
.PHONY : API.cpp.s

Ack.o: Ack.cpp.o

.PHONY : Ack.o

# target to build an object file
Ack.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Ack.cpp.o
.PHONY : Ack.cpp.o

Ack.i: Ack.cpp.i

.PHONY : Ack.i

# target to preprocess a source file
Ack.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Ack.cpp.i
.PHONY : Ack.cpp.i

Ack.s: Ack.cpp.s

.PHONY : Ack.s

# target to generate assembly for a file
Ack.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Ack.cpp.s
.PHONY : Ack.cpp.s

Handshake.o: Handshake.cpp.o

.PHONY : Handshake.o

# target to build an object file
Handshake.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Handshake.cpp.o
.PHONY : Handshake.cpp.o

Handshake.i: Handshake.cpp.i

.PHONY : Handshake.i

# target to preprocess a source file
Handshake.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Handshake.cpp.i
.PHONY : Handshake.cpp.i

Handshake.s: Handshake.cpp.s

.PHONY : Handshake.s

# target to generate assembly for a file
Handshake.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Handshake.cpp.s
.PHONY : Handshake.cpp.s

Logging.o: Logging.cpp.o

.PHONY : Logging.o

# target to build an object file
Logging.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Logging.cpp.o
.PHONY : Logging.cpp.o

Logging.i: Logging.cpp.i

.PHONY : Logging.i

# target to preprocess a source file
Logging.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Logging.cpp.i
.PHONY : Logging.cpp.i

Logging.s: Logging.cpp.s

.PHONY : Logging.s

# target to generate assembly for a file
Logging.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Logging.cpp.s
.PHONY : Logging.cpp.s

MozQuic.o: MozQuic.cpp.o

.PHONY : MozQuic.o

# target to build an object file
MozQuic.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/MozQuic.cpp.o
.PHONY : MozQuic.cpp.o

MozQuic.i: MozQuic.cpp.i

.PHONY : MozQuic.i

# target to preprocess a source file
MozQuic.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/MozQuic.cpp.i
.PHONY : MozQuic.cpp.i

MozQuic.s: MozQuic.cpp.s

.PHONY : MozQuic.s

# target to generate assembly for a file
MozQuic.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/MozQuic.cpp.s
.PHONY : MozQuic.cpp.s

NSSHelper.o: NSSHelper.cpp.o

.PHONY : NSSHelper.o

# target to build an object file
NSSHelper.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/NSSHelper.cpp.o
.PHONY : NSSHelper.cpp.o

NSSHelper.i: NSSHelper.cpp.i

.PHONY : NSSHelper.i

# target to preprocess a source file
NSSHelper.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/NSSHelper.cpp.i
.PHONY : NSSHelper.cpp.i

NSSHelper.s: NSSHelper.cpp.s

.PHONY : NSSHelper.s

# target to generate assembly for a file
NSSHelper.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/NSSHelper.cpp.s
.PHONY : NSSHelper.cpp.s

Packetization.o: Packetization.cpp.o

.PHONY : Packetization.o

# target to build an object file
Packetization.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Packetization.cpp.o
.PHONY : Packetization.cpp.o

Packetization.i: Packetization.cpp.i

.PHONY : Packetization.i

# target to preprocess a source file
Packetization.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Packetization.cpp.i
.PHONY : Packetization.cpp.i

Packetization.s: Packetization.cpp.s

.PHONY : Packetization.s

# target to generate assembly for a file
Packetization.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Packetization.cpp.s
.PHONY : Packetization.cpp.s

Ping.o: Ping.cpp.o

.PHONY : Ping.o

# target to build an object file
Ping.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Ping.cpp.o
.PHONY : Ping.cpp.o

Ping.i: Ping.cpp.i

.PHONY : Ping.i

# target to preprocess a source file
Ping.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Ping.cpp.i
.PHONY : Ping.cpp.i

Ping.s: Ping.cpp.s

.PHONY : Ping.s

# target to generate assembly for a file
Ping.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Ping.cpp.s
.PHONY : Ping.cpp.s

Sender.o: Sender.cpp.o

.PHONY : Sender.o

# target to build an object file
Sender.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Sender.cpp.o
.PHONY : Sender.cpp.o

Sender.i: Sender.cpp.i

.PHONY : Sender.i

# target to preprocess a source file
Sender.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Sender.cpp.i
.PHONY : Sender.cpp.i

Sender.s: Sender.cpp.s

.PHONY : Sender.s

# target to generate assembly for a file
Sender.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Sender.cpp.s
.PHONY : Sender.cpp.s

StatelessReset.o: StatelessReset.cpp.o

.PHONY : StatelessReset.o

# target to build an object file
StatelessReset.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/StatelessReset.cpp.o
.PHONY : StatelessReset.cpp.o

StatelessReset.i: StatelessReset.cpp.i

.PHONY : StatelessReset.i

# target to preprocess a source file
StatelessReset.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/StatelessReset.cpp.i
.PHONY : StatelessReset.cpp.i

StatelessReset.s: StatelessReset.cpp.s

.PHONY : StatelessReset.s

# target to generate assembly for a file
StatelessReset.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/StatelessReset.cpp.s
.PHONY : StatelessReset.cpp.s

Streams.o: Streams.cpp.o

.PHONY : Streams.o

# target to build an object file
Streams.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Streams.cpp.o
.PHONY : Streams.cpp.o

Streams.i: Streams.cpp.i

.PHONY : Streams.i

# target to preprocess a source file
Streams.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Streams.cpp.i
.PHONY : Streams.cpp.i

Streams.s: Streams.cpp.s

.PHONY : Streams.s

# target to generate assembly for a file
Streams.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Streams.cpp.s
.PHONY : Streams.cpp.s

Timer.o: Timer.cpp.o

.PHONY : Timer.o

# target to build an object file
Timer.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Timer.cpp.o
.PHONY : Timer.cpp.o

Timer.i: Timer.cpp.i

.PHONY : Timer.i

# target to preprocess a source file
Timer.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Timer.cpp.i
.PHONY : Timer.cpp.i

Timer.s: Timer.cpp.s

.PHONY : Timer.s

# target to generate assembly for a file
Timer.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/Timer.cpp.s
.PHONY : Timer.cpp.s

TransportExtension.o: TransportExtension.cpp.o

.PHONY : TransportExtension.o

# target to build an object file
TransportExtension.cpp.o:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/TransportExtension.cpp.o
.PHONY : TransportExtension.cpp.o

TransportExtension.i: TransportExtension.cpp.i

.PHONY : TransportExtension.i

# target to preprocess a source file
TransportExtension.cpp.i:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/TransportExtension.cpp.i
.PHONY : TransportExtension.cpp.i

TransportExtension.s: TransportExtension.cpp.s

.PHONY : TransportExtension.s

# target to generate assembly for a file
TransportExtension.cpp.s:
	$(MAKE) -f CMakeFiles/mozquic.dir/build.make CMakeFiles/mozquic.dir/TransportExtension.cpp.s
.PHONY : TransportExtension.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... mozquic"
	@echo "... edit_cache"
	@echo "... API.o"
	@echo "... API.i"
	@echo "... API.s"
	@echo "... Ack.o"
	@echo "... Ack.i"
	@echo "... Ack.s"
	@echo "... Handshake.o"
	@echo "... Handshake.i"
	@echo "... Handshake.s"
	@echo "... Logging.o"
	@echo "... Logging.i"
	@echo "... Logging.s"
	@echo "... MozQuic.o"
	@echo "... MozQuic.i"
	@echo "... MozQuic.s"
	@echo "... NSSHelper.o"
	@echo "... NSSHelper.i"
	@echo "... NSSHelper.s"
	@echo "... Packetization.o"
	@echo "... Packetization.i"
	@echo "... Packetization.s"
	@echo "... Ping.o"
	@echo "... Ping.i"
	@echo "... Ping.s"
	@echo "... Sender.o"
	@echo "... Sender.i"
	@echo "... Sender.s"
	@echo "... StatelessReset.o"
	@echo "... StatelessReset.i"
	@echo "... StatelessReset.s"
	@echo "... Streams.o"
	@echo "... Streams.i"
	@echo "... Streams.s"
	@echo "... Timer.o"
	@echo "... Timer.i"
	@echo "... Timer.s"
	@echo "... TransportExtension.o"
	@echo "... TransportExtension.i"
	@echo "... TransportExtension.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

